//Buscar produtos
GET http://localhost:5005/produtos

###

//criar produto

POST  http://localhost:5005/produto
Content-Type: application/json

{
    "valor": 200,
    "off": 12
}

###

// Buscar produto por ID

GET http://localhost:5005/produto/2

###
// atulizar prudto
PATCH   http://localhost:5005/produto/2
Content-Type: application/json

{
    "nome": "produdo 1 atulizar",
    "valor": 240
}
###
//remover todos
DELETE http://localhost:5005/produtos
###
// remover por id 
DELETE http://localhost:5005/produto/2